name: ringo
description: Yarışma ve ekip kurma odaklı sosyal medya platformu.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.0
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  riverpod_annotation: ^2.6.1
  supabase_flutter: ^1.5.0

dependency_overrides:
  sign_in_with_apple: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ringo_logo_bg.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
